<a href="https://colab.research.google.com/github/laceywang11/MSSP6070/blob/main/Participation_Week_6_Exercise_Lacey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A. Import Files

In [5]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Student Performance Data.csv")
df.head()

Saving Student Performance Data.csv to Student Performance Data.csv

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

B. Convert to Numeric

In [6]:
for col in ["math score", "reading score", "writing score", "total score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

C. Transform DataFrame

In [7]:
Transform_df = lambda d:(
    d.assign(
        Average_score = lambda x:x[["math score", "reading score", "writing score"]].mean(axis=1),
        Grade = lambda x:x.apply(
            lambda s: "A" if s["total score"] >= 270
            else "B" if s["total score"] >= 240
            else "C" if s["total score"] >= 210
            else "D", axis=1),
        Percentage = lambda x:(x["total score"].rank(pct=True) * 100)
    )
)

D. Print New DataFrame

In [9]:
Transform_df(df)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,Average_score,Grade,Percentage
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.666667,C,61.75
1,female,group C,some college,standard,69,90,88,247,completed,high,82.333333,B,84.10
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.666667,A,96.90
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.333333,D,9.85
4,male,group C,some college,standard,76,78,75,229,none,high,76.333333,C,71.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,99,95,282,completed,high,94.000000,A,97.65
996,male,group C,high school,free/reduced,62,55,55,172,none,medium,57.333333,D,23.35
997,female,group C,high school,free/reduced,59,71,65,195,completed,medium,65.000000,D,40.40
998,female,group D,some college,standard,68,78,77,223,completed,high,74.333333,C,66.25
999,female,group D,some college,free/reduced,77,86,86,249,none,high,83.000000,B,85.70